language: node_js

node_js:
  - '7'
  - '4'

branches:
  only:
    - master

addons:
  sauce_connect: true

script:
  - npm test
  - if [[ "$TRAVIS_NODE_VERSION" == "4" ]]; then npm run test:browser; fi

after_script:
  - if [[ "$TRAVIS_NODE_VERSION" == "4" ]]; then npm run coverage; fi