language: node_js

matrix:
  fast_finish: true
  include:
    - env: TEST='node'
      node_js:
        - '7'
        - '4'
    - env: TEST='browser'
      node_js: '4'
  allow_failures:
    - env: TEST='browser'

addons:
  sauce_connect: 
    no_ssl_bump_domains: *

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

deploy:
  provider: npm
  email: iegoroff@gmail.com
  api_key:
    secure: "MtvFwnXyUN+c6LzPaD3cH/8PC6L/D6aouYlY/9ZOtlKIXMPQNVWByhygJuBgvOCp8kwqDSQyS3E2cKpHRr9sq6KfV+gyjufEvvL+V3EiXuKfCcLbIGPPRZVZKMJ1Har4X1w+WHc1wgknFNFETnnwTaBQO5RaQKPzsyrxASzVbpeu4nR9LNk5qhXgl72dNEpzPUwhuDR0nWQwzfGMMWpofC4m/Z4jiZpPqkkXWIXLfxF5aCDjAtooEPl5w16IB1bzD03CbtpuYmvu7lMBpyZeGASQPylNS+sApG+S/WGP/vjUOd8pKk4ozZWdkAJdJ9/nXpsbEdK8wXzIoxFD9qkxnIvpQG4xJ7qQUzrdkaVZYmuSHkVNbUBeyqkTalbuTVHZtQWHWZMLxwQiL85fURhInM4JzjmzNjnwGbXrDxoaputkk3JTUrm4RXJEqYKlHfgEx0gLhpzQec83nuWpH9yk+8HZw9aGEnHLPwtw6VmgnX9BSBpoCXSVMAXc1MXNn7OdEv9QrIKOpX/5miJgcf9bLTnUjXg8cjsqoBsDg9AhfGe5wF6A0LEeUdBc/5xVFXZZY7gtWef7yfwgKamj7hjQ6vezWI6DPJl8CSZEWwjThi9dd1KM2V/EFt2HwDorYLJe4g0B02kwNBB6j8e2PzKrLwLSL9OQAs4taBFD8octs6w="
  on:
    tags: true
    condition: $TEST == 'node'


before_script:
  - npm run build

script:
  - if [[ $TEST == 'node' ]]; then npm run lint && npm run test:node; fi
  - if [[ $TEST == 'browser' ]]; then npm run test:browser; fi
after_script:
  - if [[ $TEST == 'node' ]]; then npm run coverage; fi
  
