language: node_js

matrix:
  fast_finish: true
  include:
    - env: TEST='node'
      node_js:
        - '7'
        - '4'
    - env: TEST='browser'
      node_js: '4'
  allow_failures:
    - env: TEST='browser'

addons:
  sauce_connect:
    username: 'iyegoroff-2'
    no_ssl_bump_domains: 127.0.0.1
  jwt:
    secure: >
      Qem8r6E/89fgnozXLbCr2LSrUVDRc2zXjyxZl8ZMRpBWD4eycnJOZqQxiE2l7EckvoFcM/X8Y4oByOnbdzQW7ngaKjJdqcQ440/GO2T6w1G6XE47C
      X1A63P1Xl0RTFU1WvcZRwRO0S9NtQyaVc5JixSKDeHJJErTc9NeWA5BuE9H2qOFm/dH00uDAs/QfD5A8HLz/GEQ0KSzOkZZuZRChCZ8KjtzVK7e/Q
      N6INrK5Jd+kuhXDtOhFIu693NuFHi6A83c1ey0O9kOCxhOynmlEMtjb69Kv2+n5Gb8KStCMP6sBD/bpn8u2d8OgvNQbkhf05IYu2H5mZAW0vVo2ld
      jwYDCBezXOckxgJ3vItxh57Pq8owf0JOiy5XXMLG3TOtz82MIf1BhZS1QXVGVN1fj4nj9u41tPDyeH3+S8J0i+wXwRT3ZL44c9PQ9IsfjKqglIM3w
      Yn6ie0JH8/YIa92jsKOL4EA1mGtZ0RGwkR7VF+BJWkXDZlaSfFK7bfG8wiCR1XY3Dj5RglMmUlRTZflZdR/vxb1kLplS6B+smIJwewSanAOnbtynm
      ocBM2np+MixwzH7CTlNcGuerXD3VlEjyLkGY17GRLiKe7He0Sk+iC2h+TdJ9Ho9xHDRfzorP3ADbubDNmiKqtTo96lmkb4y+fZQV4mKzTamHXsZ8Y
      FwsGQ=

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

deploy:
  provider: npm
  email: iegoroff@gmail.com
  api_key:
    secure: >
      rgVtzou3HLvS3hkwL0e8ji8bYqesshnNkvslOKVxp61VUB2RKGni3SWKXbPRRxO9Cy+CelvNjkzzekQSHftI8dChuim4sj3Cobf/0bcDtvMUgYLF1
      EJS0UJ2cVrhTsdkerJO7/Ai5gK1Mh5TsfYaWI6+OfA4MOrHeBVeNcSKKqkEWJQ627tMa3BTZ9/kn2YCROR7siJFsprkhNo0ZkF9u6wOLAKzPDWNhG
      lAvqp7x+erWuOquhKvA1rCj1joyT8vLVN02u2zZbzfNrIsIveghBhvEAw7hVU1Urp3rJ2xVjRGA0co0uLH6tVfBlTiXmI/jDzqMrDpq6EnDuig1ML
      NIDZ6hXozOLnYSryvau5ZqeQky94X0TylextK9kIH+4Y4zpgocp+6x+iUG6mfalbHnqRPJGxIBzFQwEUBU96L9PPBOcfBv5yQ6VolHrU0Xtwch5EP
      nrn+Xwyi4VAMYFUjNhqi6ORcS/J/i+Ka+8DT/kr0IkqhdwW6AsrA80EmAdddYMQj/798uyar23VU4jAp0Kcuxf+xaaPHbrwVtVW3k77XfM8Ex3boM
      cm4xZF0wlOojUNejB9aF99CgSQLFXp9iNik3A6wnC09BBNIJ2VKWruhhHzvKqUhSDNp801cB9SU+RBAXBGavpQajZMSU6P9M2hpIJWQiL0TNSggF6
      DN2sY=
  on:
    tags: true
    condition: $TEST == 'node'


before_script:
  - npm run build

script:
  - if [[ $TEST == 'node' ]]; then npm run lint && npm run test:node; fi
  - if [[ $TEST == 'browser' ]]; then npm run test:browser; fi
after_script:
  - if [[ $TEST == 'node' ]]; then npm run coverage; fi
  
